[project]
name = "teslamate-telegram-bot"
revision = "0.7.9"

[profiles.default]
CAR_ID = { description = "numeric ID of the car to listen to", required = false, default = "1"}
MQTT_BROKER_HOST = { description = "IP of the MQTT Broker Host", required = false, default = "127.0.0.1"}
MQTT_BROKER_PORT = { description = "Port of the MQTT Broker Host", required = false, default = "1883"}
MQTT_BROKER_USERNAME = { description = "Username for MQTT Broker, only needed when broker has authentication enabled", required = false }
MQTT_BROKER_PASSWORD = { description = "Password for MQTT Broker, only needed when broker has authentication enabled", required = false }
MQTT_NAMESPACE = { description = "MQTT namespace to use, only needed when you specified MQTT_NAMESPACE on your TeslaMate installation", required = false }
TELEGRAM_BOT_API_KEY = { description = "Unique authentication token of your telegram bot", required = true }
TELEGRAM_BOT_CHAT_ID = { description = "Chat ID where the bot should messages to", required = true }